### ISSUE TITLE
Add P-chain config for cache sizes

### ISSUE THREAD

**Issue by StephenButtolph** [ava-labs/avalanchego#1522]
**Context and scope**
Currently the P-chain is solely configured by avalanchego level configurations. Until now this has made sense, because the configurations generally impacted the entire node. However, there has been some recent interest to introduce more granular P-chain configs for (ex) API optimizations. Specifically allowing the node operator to specify P-chain state cache sizes would be useful.

**TODO**
- [ ] Allow configuration of [cache sizes](https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/state/state.go#L42-L49) when creating an instance of the platformvm state
- [ ] Define a platformvm json config with default values
- [ ] Override default config values from the [`configBytes`](https://github.com/ava-labs/avalanchego/blob/master/snow/engine/common/vm.go#L52)

**Comment by najeal** [comment]
I am going to work on this issue.
