### ISSUE TITLE
Migrate Kurtosis Tests

### ISSUE THREAD

**Issue by danlaine** [ava-labs/avalanchego#1547]
**Context and scope**

Remove Kurtosis tests and replace them with Ginkgo tests.

Namely, we should have the following test cases:

* ~[ ] A network where one or more nodes is sending `AppGossip`, `AppRequest` and `AppResponse` with random payloads to other nodes. The nodes shouldn't crash.~
  * Deferred until after Kurtosis deprecation due to the deprecation of the avalanche-byzantine docker image
  * Existing test: [RandomAppMsgs](https://github.com/ava-labs/avalanche-testing/blob/master/tests/random_app_msgs.go#L34)
* [x] A network where multiple nodes have the same node ID (i.e. the same staking key/cert pair). All other nodes in the network should be connected to only one of the nodes that share a node ID.
  * Existing test: [DuplicateNodeID](https://github.com/ava-labs/avalanche-testing/blob/master/tests/duplicate_node_id.go#L31)
  * PR: https://github.com/ava-labs/avalanchego/pull/1573
* [x] A network where 2 nodes become validators. One remains online, and the other shuts down. After the end of the staking periods, the one that was online should have received a reward, and the other shouldn't have.
  * Existing test: [StakingRewardTests](https://github.com/ava-labs/avalanche-testing/blob/master/tests/rewards.go#L29)
  * PR: https://github.com/ava-labs/avalanchego/pull/1767
* [x] A C-Chain dynamic fees test where we assert that when gas usage is high, the gas price increases, and when gas usage decreases, the gas price decreases.
  * Existing test: [DynamicFees](https://github.com/ava-labs/avalanche-testing/blob/master/tests/dynfees/dynfees.go#L32)
  * PR: https://github.com/ava-labs/avalanchego/pull/1792
* [x] An X-Chain workflow test where we send funds from one address to another, and do import/export transactions to the C-Chain and P-Chain.
  * No existing test
  * PR: https://github.com/ava-labs/avalanchego/pull/1871
* [x] A C-Chain workflow test where we send funds from one address to another, and do import/export transactions to the X-Chain and P-Chain.
  * No existing test 
  * PR: https://github.com/ava-labs/avalanchego/pull/1871
* [x] A P-Chain workflow test where we add a node to the validator set, add a delegator for that node, and do import/export transactions to the X-Chain and C-Chain.
  * No existing test
  * PR: https://github.com/ava-labs/avalanchego/pull/1882

# TODO

- [x] Merge test PRs
- [x] Ensure that new tests check that bootstrap is possible with the network state produced by the test
  - [x] PR: https://github.com/ava-labs/avalanchego/pull/1935
- [ ] Ensure coreth repo has been updated to run the new tests
  - [x] PR: https://github.com/ava-labs/coreth/pull/305
  - [ ] PR: https://github.com/ava-labs/coreth/pull/344
- [ ] Remove Kurtosis jobs from avalanche repo
  - [ ] PR: https://github.com/ava-labs/avalanchego/pull/2068 
- [ ] Remove Kurtosis job from coreth repo
  - [ ] PR: https://github.com/ava-labs/coreth/pull/345

**Comment by aaronbuchwald** [comment]
We should make sure that after each of these tests, we are starting a new node to join the network to ensure that it can bootstrap the data produced by the e2e test.
